### ISSUE TITLE
bool value parsing

### ISSUE THREAD

**Issue by akashirin** [crgimenes/goconfig#43] opened 2019-07-09 19:30 UTC
```
package main

import (
	"github.com/crgimenes/goconfig"
	_ "github.com/crgimenes/goconfig/ini"
	_ "github.com/crgimenes/goconfig/json"
)

type config struct {
	Foo bool `json:"FOO" ini:"FOO" cfg:"FOO" cfgDefault:"true"`
}

/*
env.ini:
	FOO=false
*/
func ckINI() {
	goconfig.Path = "."
	goconfig.File = "env.ini"

	c := &config{}
	_ = goconfig.Parse(c)
	println("Foo:", c.Foo) // Foo: true    (!!! must be false)
}

/*
env.json:
	{"FOO": false}
*/
func ckJSON() {
	goconfig.Path = "."
	goconfig.File = "env.json"

	c := &config{}
	_ = goconfig.Parse(c)
	println("Foo:", c.Foo) // Foo: true    (!!! must be false)
}

func main() {
	ckINI()
	ckJSON()
}

```

**Comment by crgimenes** [comment] 2019-07-09 23:04
You're right, it's a bug. 
The problem only occurs when the default value is true. 

When trying to parse the environment variables the goconfig can not distinguish whether the false value came from. Does not know if it already came from the configuration file or if it was not declared and therefore should use the default value. So the result always ends up being "true".

I need to figure out a way to find out where the value is coming from, but this is not a trivial problem.

**Comment by akashirin** [comment] 2019-07-10 07:28
Most probably the following fixes this issue:

github.com/crgimenes/goconfig/goenv/goenv.go:

func parseValue(datatype string, value *reflect.Value) (ret string, ok
bool) {
    switch datatype {
    case "bool":
        if value.Bool() {
            ret = "true"
            ok = true
        }
    case "string":
    ...
    }
    return
}

MUST BE:
    case "bool":
        ret = strconv.FormatBool(value.Bool())
        ok = true

-- regards

**Comment by crgimenes** [comment] 2019-07-10 14:11
With this goconfig will respect the file but the default value will not work.

For example, if the env.json file does not contain the FOO field, the default value will be ignored and the result will always be false.

The problem still the same. It is to know if the value is the default of Go when the structure was instantiated or if it came from the configuration file.

In other types we do this comparing with empty string `""` or with `"0"` but in the case of bool we can not do this comparison.

Basically, the variable value `ok` should be `false` if it came from a configuration file or defined in the structure instance, otherwise it should be `true`. If it always returns `true` it will always use the current value and if it always returns `false` it will always return the cfgDefault value.

I'm wondering if it's not better to remove the default support for boolean fields and leave it as Go itself, where the default is always false.

I made the changes you suggested, I am testing alternatives in this branch:
https://github.com/crgimenes/goconfig/tree/issue_43

But as I said the problem is the value returned in the `ok` variable

**Comment by crgimenes** [comment] 2019-07-15 00:58
fixed by PR [44](https://github.com/crgimenes/goconfig/pull/44)

**Closed by crgimenes** 2019-07-15 00:58 UTC
Labels: bug, help wanted
